### ISSUE TITLE
implement assign user management dashboard

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#124]
* [x] create a route to manage users `/manage-user` #155 
* [x] implement a link in the **top menu** with the label *Manage Users** which should be hidden when the user is not logged in. (See _Dashboard_) #156 
* [x] grab the users from the database from the `user` collection and display them in a vertical list, showing their: **displayName**, **email** and **photoUrl** #157
