### ISSUE TITLE
feat: add youtube presentation features

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#142]
* [x] add YouTube list Id to the course #144 
* [x] make course title manageable from the course route #148
* [x] make course description manageable from the course route #149 
* [x] add YouTube video Id to the lecture #145
* [x] generate YouTube preview using the default image from YouTube thumbnail if no image is currently uploaded for the current lecture #146
* [x] add a **Watch this Course NOW** button next to the title of the course in the home page #147
