### ISSUE TITLE
feat: create play video component 

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#143]
* [x] create a route **/video/:[youtubeVideoId]** that will load the **play-video** component #159
* [x] show a video to be played that is loaded from YouTube in an embed #160
* [x] show a playlist with the current video selected #161
* [x] the playlist can be toggled on or off #162
