### ISSUE TITLE
feat: comments on the video page

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#158]
This section is present on the page a video can be viewed by our users!

* [x] create an additional comment section to the video form #163 
* [ ] allow adding a comment as a reply to another comment #164 
* [x] display a list of comments below #165
