### ISSUE TITLE
feat: add order to lecture

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#171]
* [x] allow lectures to automatically get a value for the order property upon creation #189
* [x] allow lectures to be reordered by drag and drop inside sections #190
* [ ] allow lectures to be moved from one section to another #191
