### ISSUE TITLE
feat: improve the home page

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#240]
* [x] feat: create a list of course descriptions that point to a playlist #241 
* [x] feat: the course description should have one image, title and what a user would get if he follows the course #242 
* [x] feat: the course description should present the time as the sum of all lectures inside it #243 
* [x] feat: the course should present the author #244 
* [x] feat: the difficulty (STARTER|JUNIOR|MID|SENIOR) a user should mind when consuming the course #245 
* [x] feat: add duration to the lecture #246
* [x] feat: implement a level pill #248
* [x] feat: course description max height #249
* [x] feat: partial duration for home page #250
